# Alberta

In [1]:
import pandas as pd
from statsmodels.tsa.api import VAR
from statsmodels.tsa.stattools import adfuller

# Assuming 'ConstructionBreton' is your DataFrame containing the data
ConstructionBreton = pd.read_csv('Final.csv')
Construction_Breton = ConstructionBreton[ConstructionBreton['Station Name'] == 'Breton']
Construction_Breton.set_index('Date', inplace=True)

# Selecting columns to include in the analysis, excluding 'provincename', 'Population', 'Station Name', 'Longitude (x)', and 'Latitude (y)'
variables = Construction_Breton.drop(columns=['provincename', 'Population','Transportation','Agriculture', 'Station Name', 'Longitude (x)', 'Latitude (y)','Heat Deg Days (°C)','Cool Deg Days (°C)','Min Temp (°C)','Max Temp (°C)'])

# Check for stationarity using Augmented Dickey-Fuller test
for column in variables.columns:
    result = adfuller(variables[column])
    print(f'ADF Statistic for {column}: {result[0]}')
    print(f'p-value: {result[1]}')

# Define lag order for VAR model
lag_order = 2  # Adjust as needed

# Fit VAR model
model = VAR(variables)
results = model.fit(lag_order)

# Print summary of the model
print(results.summary())

# Forecast future values
forecast = results.forecast(variables.values[-lag_order:], steps=5)  # Adjust 'steps' for desired forecast horizon
print(forecast)


ADF Statistic for Construction: -1.7617018048350697
p-value: 0.39963451439398834
ADF Statistic for Total Snow (cm): -1.345431345544066
p-value: 0.6081398070983577
ADF Statistic for Total Precip (mm): -2.438811488942146
p-value: 0.13108036871242945
ADF Statistic for MeanTemp: -4.213774123127767
p-value: 0.0006244048004903148
  Summary of Regression Results   
Model:                         VAR
Method:                        OLS
Date:           Mon, 08, Apr, 2024
Time:                     00:25:37
--------------------------------------------------------------------
No. of Equations:         4.00000    BIC:                    2.36054
Nobs:                     250.000    HQIC:                   2.05753
Log likelihood:          -1614.62    FPE:                    6.38256
AIC:                      1.85345    Det(Omega_mle):         5.54059
--------------------------------------------------------------------
Results for equation Construction
                          coefficient       std. er

C:\Users\PC\anaconda3\envs\MachineLearning2\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  self._init_dates(dates, freq)


In [2]:
import pandas as pd
from statsmodels.tsa.api import VAR
from statsmodels.tsa.stattools import adfuller

# Assuming 'ConstructionBreton' is your DataFrame containing the data
TransportationStavely = pd.read_csv('Final.csv')
Transportation_Stavely = TransportationStavely[TransportationStavely['Station Name'] == 'Stavely']
Transportation_Stavely.set_index('Date', inplace=True)

# Selecting columns to include in the analysis, excluding 'provincename', 'Population', 'Station Name', 'Longitude (x)', and 'Latitude (y)'
variables = Transportation_Stavely.drop(columns=['provincename', 'Population','Transportation','Construction' ,'Station Name', 'Longitude (x)', 'Latitude (y)','Heat Deg Days (°C)','Cool Deg Days (°C)','Min Temp (°C)','Max Temp (°C)'])

# Check for stationarity using Augmented Dickey-Fuller test
for column in variables.columns:
    result = adfuller(variables[column])
    print(f'ADF Statistic for {column}: {result[0]}')
    print(f'p-value: {result[1]}')

# Define lag order for VAR model
lag_order = 1  # Adjust as needed

# Fit VAR model
model = VAR(variables)
results = model.fit(lag_order)

# Print summary of the model
print(results.summary())

# Forecast future values
forecast = results.forecast(variables.values[-lag_order:], steps=5)  # Adjust 'steps' for desired forecast horizon
forecast


ADF Statistic for Agriculture: -1.3905081663397558
p-value: 0.5868180685930477
ADF Statistic for Total Snow (cm): -3.964595238245201
p-value: 0.001607679671784117
ADF Statistic for Total Precip (mm): -16.217389865358378
p-value: 3.9296739452331394e-29
ADF Statistic for MeanTemp: -3.1249253985929446
p-value: 0.024762748460614915
  Summary of Regression Results   
Model:                         VAR
Method:                        OLS
Date:           Mon, 08, Apr, 2024
Time:                     00:25:38
--------------------------------------------------------------------
No. of Equations:         4.00000    BIC:                    1.74964
Nobs:                     251.000    HQIC:                   1.58178
Log likelihood:          -1588.94    FPE:                    4.34381
AIC:                      1.46873    Det(Omega_mle):         4.01426
--------------------------------------------------------------------
Results for equation Agriculture
                          coefficient       std.

C:\Users\PC\anaconda3\envs\MachineLearning2\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  self._init_dates(dates, freq)


array([[11.72352276,  0.2628773 ,  0.37167393,  5.31343906],
       [11.66688629,  0.32237328,  0.3981363 ,  5.27582671],
       [11.61281242,  0.37565152,  0.44888088,  5.24694314],
       [11.56081662,  0.42362064,  0.4920558 ,  5.2259001 ],
       [11.51081256,  0.46680017,  0.53105387,  5.20992671]])

In [3]:
import pandas as pd
from statsmodels.tsa.api import VAR
from statsmodels.tsa.stattools import adfuller

# Assuming 'ConstructionBreton' is your DataFrame containing the data
AgricultureMilkriver = pd.read_csv('Final.csv')
Agriculture_Milkriver = AgricultureMilkriver[AgricultureMilkriver['Station Name'] == 'Stavely']
Agriculture_Milkriver.set_index('Date', inplace=True)

# Selecting columns to include in the analysis, excluding 'provincename', 'Population', 'Station Name', 'Longitude (x)', and 'Latitude (y)'
variables = Agriculture_Milkriver.drop(columns=['provincename', 'Population','Transportation','Construction' ,'Station Name', 'Longitude (x)', 'Latitude (y)','Heat Deg Days (°C)','Cool Deg Days (°C)','Min Temp (°C)','Max Temp (°C)'])

# Check for stationarity using Augmented Dickey-Fuller test
for column in variables.columns:
    result = adfuller(variables[column])
    print(f'ADF Statistic for {column}: {result[0]}')
    print(f'p-value: {result[1]}')

# Define lag order for VAR model
lag_order = 1  # Adjust as needed

# Fit VAR model
model = VAR(variables)
results = model.fit(lag_order)

# Print summary of the model
print(results.summary())

# Forecast future values
forecast = results.forecast(variables.values[-lag_order:], steps=5)  # Adjust 'steps' for desired forecast horizon
forecast


C:\Users\PC\anaconda3\envs\MachineLearning2\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  self._init_dates(dates, freq)


ADF Statistic for Agriculture: -1.3905081663397558
p-value: 0.5868180685930477
ADF Statistic for Total Snow (cm): -3.964595238245201
p-value: 0.001607679671784117
ADF Statistic for Total Precip (mm): -16.217389865358378
p-value: 3.9296739452331394e-29
ADF Statistic for MeanTemp: -3.1249253985929446
p-value: 0.024762748460614915
  Summary of Regression Results   
Model:                         VAR
Method:                        OLS
Date:           Mon, 08, Apr, 2024
Time:                     00:25:38
--------------------------------------------------------------------
No. of Equations:         4.00000    BIC:                    1.74964
Nobs:                     251.000    HQIC:                   1.58178
Log likelihood:          -1588.94    FPE:                    4.34381
AIC:                      1.46873    Det(Omega_mle):         4.01426
--------------------------------------------------------------------
Results for equation Agriculture
                          coefficient       std.

array([[11.72352276,  0.2628773 ,  0.37167393,  5.31343906],
       [11.66688629,  0.32237328,  0.3981363 ,  5.27582671],
       [11.61281242,  0.37565152,  0.44888088,  5.24694314],
       [11.56081662,  0.42362064,  0.4920558 ,  5.2259001 ],
       [11.51081256,  0.46680017,  0.53105387,  5.20992671]])

# BC

In [4]:
import pandas as pd
from statsmodels.tsa.api import VAR
from statsmodels.tsa.stattools import adfuller

# Assuming 'ConstructionBreton' is your DataFrame containing the data
ConstructionBurnsLake = pd.read_csv('FinalBC.csv')
Construction_BurnsLake = ConstructionBurnsLake[ConstructionBurnsLake['Station Name'] == 'Burns Lake']
Construction_BurnsLake.set_index('Date', inplace=True)

# Selecting columns to include in the analysis, excluding 'provincename', 'Population', 'Station Name', 'Longitude (x)', and 'Latitude (y)'
variables = Construction_BurnsLake.drop(columns=['provincename', 'Population','Transportation','Agriculture', 'Station Name', 'Longitude (x)', 'Latitude (y)','Heat Deg Days (°C)','Cool Deg Days (°C)','Min Temp (°C)','Max Temp (°C)'])

# Check for stationarity using Augmented Dickey-Fuller test
for column in variables.columns:
    result = adfuller(variables[column])
    print(f'ADF Statistic for {column}: {result[0]}')
    print(f'p-value: {result[1]}')

# Define lag order for VAR model
lag_order = 2  # Adjust as needed

# Fit VAR model
model = VAR(variables)
results = model.fit(lag_order)

# Print summary of the model
print(results.summary())

# Forecast future values
forecast = results.forecast(variables.values[-lag_order:], steps=5)  # Adjust 'steps' for desired forecast horizon
print(forecast)


ADF Statistic for Construction: -0.06736803716042235
p-value: 0.9525933566957034
ADF Statistic for Total Snow (cm): -2.430073289352188
p-value: 0.13342769807782057
ADF Statistic for Total Precip (mm): -14.50781676547278
p-value: 5.79017346943901e-27
ADF Statistic for Mean Temp (°C): -3.3910026414057453
p-value: 0.011269441746674774
  Summary of Regression Results   
Model:                         VAR
Method:                        OLS
Date:           Mon, 08, Apr, 2024
Time:                     00:25:38
--------------------------------------------------------------------
No. of Equations:         4.00000    BIC:                   -2.53853
Nobs:                     250.000    HQIC:                  -2.84153
Log likelihood:          -1002.24    FPE:                  0.0475729
AIC:                     -3.04562    Det(Omega_mle):       0.0412972
--------------------------------------------------------------------
Results for equation Construction
                          coefficient      

C:\Users\PC\anaconda3\envs\MachineLearning2\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  self._init_dates(dates, freq)


In [5]:
import pandas as pd
from statsmodels.tsa.api import VAR
from statsmodels.tsa.stattools import adfuller

# Assuming 'ConstructionBreton' is your DataFrame containing the data
TransportationKootenay = pd.read_csv('FinalBC.csv')
Transportation_Kootenay = TransportationKootenay[TransportationKootenay['Station Name'] == 'Kootenay']
Transportation_Kootenay.set_index('Date', inplace=True)

# Selecting columns to include in the analysis, excluding 'provincename', 'Population', 'Station Name', 'Longitude (x)', and 'Latitude (y)'
variables = Transportation_Kootenay.drop(columns=['provincename', 'Population','Agriculture','Construction', 'Station Name', 'Longitude (x)', 'Latitude (y)','Heat Deg Days (°C)','Cool Deg Days (°C)','Min Temp (°C)','Max Temp (°C)'])

# Check for stationarity using Augmented Dickey-Fuller test
for column in variables.columns:
    result = adfuller(variables[column])
    print(f'ADF Statistic for {column}: {result[0]}')
    print(f'p-value: {result[1]}')

# Define lag order for VAR model
lag_order = 2  # Adjust as needed

# Fit VAR model
model = VAR(variables)
results = model.fit(lag_order)

# Print summary of the model
print(results.summary())

# Forecast future values
forecast = results.forecast(variables.values[-lag_order:], steps=5)  # Adjust 'steps' for desired forecast horizon
forecast


ADF Statistic for Transportation: -1.4681859728736606
p-value: 0.5491865066338074
ADF Statistic for Total Snow (cm): -3.8366581292411706
p-value: 0.002553752604585045
ADF Statistic for Total Precip (mm): -13.681969323180635
p-value: 1.395079122248789e-25
ADF Statistic for Mean Temp (°C): -3.0970141523741583
p-value: 0.026774945125258562
  Summary of Regression Results   
Model:                         VAR
Method:                        OLS
Date:           Mon, 08, Apr, 2024
Time:                     00:25:38
--------------------------------------------------------------------
No. of Equations:         4.00000    BIC:                  -0.837649
Nobs:                     250.000    HQIC:                  -1.14065
Log likelihood:          -1214.85    FPE:                   0.260640
AIC:                     -1.34474    Det(Omega_mle):        0.226257
--------------------------------------------------------------------
Results for equation Transportation
                          coefficien

C:\Users\PC\anaconda3\envs\MachineLearning2\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  self._init_dates(dates, freq)


array([[1.49908525, 1.7086406 , 1.3672    , 3.97724313],
       [1.49009824, 1.79890749, 1.6337896 , 3.32345965],
       [1.48690864, 1.83241474, 1.92028664, 2.30597618],
       [1.4817021 , 1.85890301, 1.95669711, 1.53625482],
       [1.47656004, 1.88637917, 1.94703059, 1.07478189]])

In [6]:
import pandas as pd
from statsmodels.tsa.api import VAR
from statsmodels.tsa.stattools import adfuller

# Assuming 'ConstructionBreton' is your DataFrame containing the data
AgriculturePemberton = pd.read_csv('FinalBC.csv')
Agriculture_Pemberton = AgriculturePemberton[AgriculturePemberton['Station Name'] == 'Pemberton']
Agriculture_Pemberton.set_index('Date', inplace=True)

# Selecting columns to include in the analysis, excluding 'provincename', 'Population', 'Station Name', 'Longitude (x)', and 'Latitude (y)'
variables = Agriculture_Pemberton.drop(columns=['provincename', 'Population','Transportation','Construction', 'Station Name', 'Longitude (x)', 'Latitude (y)','Heat Deg Days (°C)','Cool Deg Days (°C)','Min Temp (°C)','Max Temp (°C)'])

# Check for stationarity using Augmented Dickey-Fuller test
for column in variables.columns:
    result = adfuller(variables[column])
    print(f'ADF Statistic for {column}: {result[0]}')
    print(f'p-value: {result[1]}')

# Define lag order for VAR model
lag_order = 1  # Adjust as needed

# Fit VAR model
model = VAR(variables)
results = model.fit(lag_order)

# Print summary of the model
print(results.summary())

# Forecast future values
forecast = results.forecast(variables.values[-lag_order:], steps=5)  # Adjust 'steps' for desired forecast horizon
forecast


ADF Statistic for Agriculture: -1.5212373732986268
p-value: 0.5229805814759486
ADF Statistic for Total Snow (cm): -2.8003024967880017
p-value: 0.058230571545839625
ADF Statistic for Total Precip (mm): -14.715841091863897
p-value: 2.800940423439978e-27
ADF Statistic for Mean Temp (°C): -1.9691529036353095
p-value: 0.3002600598396086
  Summary of Regression Results   
Model:                         VAR
Method:                        OLS
Date:           Mon, 08, Apr, 2024
Time:                     00:25:39
--------------------------------------------------------------------
No. of Equations:         4.00000    BIC:                    6.72085
Nobs:                     251.000    HQIC:                   6.55298
Log likelihood:          -2212.83    FPE:                    626.378
AIC:                      6.43993    Det(Omega_mle):         578.858
--------------------------------------------------------------------
Results for equation Agriculture
                          coefficient       

C:\Users\PC\anaconda3\envs\MachineLearning2\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  self._init_dates(dates, freq)


array([[15.50908444,  8.32522881,  2.08883543,  3.52511626],
       [15.09160509,  7.8628262 , 10.62483224,  3.96450661],
       [14.76075114,  7.44338902,  8.46613924,  3.94705297],
       [14.48128264,  7.05578371,  8.3181955 ,  4.09729903],
       [14.24857906,  6.69960923,  7.83365125,  4.27310685]])

# Ontario

In [21]:
import pandas as pd
from statsmodels.tsa.api import VAR
from statsmodels.tsa.stattools import adfuller


AgricultureMoosone = pd.read_excel('FinalON.xlsx')
Agriculture_Moosone = AgricultureMoosone[AgricultureMoosone['Station Name'] == 'Moosone']
Agriculture_Moosone.set_index('Date', inplace=True)

# Selecting columns to include in the analysis, excluding 'provincename', 'Population', 'Station Name', 'Longitude (x)', and 'Latitude (y)'
variables = Agriculture_Moosone.drop(columns=['provincename', 'Population','Transportation','Construction' ,'Station Name', 'Longitude (x)', 'Latitude (y)'])

# Check for stationarity using Augmented Dickey-Fuller test
for column in variables.columns:
    result = adfuller(variables[column])
    print(f'ADF Statistic for {column}: {result[0]}')
    print(f'p-value: {result[1]}')

# Define lag order for VAR model
lag_order = 2  # Adjust as needed

# Fit VAR model
model = VAR(variables)
results = model.fit(lag_order)

# Print summary of the model
print(results.summary())

# Forecast future values
forecast = results.forecast(variables.values[-lag_order:], steps=5)  # Adjust 'steps' for desired forecast horizon
forecast


ADF Statistic for Agriculture: -4.050160438189781
p-value: 0.001169472859197329
ADF Statistic for Max Temp (°C): -2.5114354063032374
p-value: 0.11271670157156038
ADF Statistic for Total Snow (cm): -1.8488106503957829
p-value: 0.3565117031348257
ADF Statistic for Total Precip (mm): -10.431308965917985
p-value: 1.608045712307249e-18
ADF Statistic for Min Temp (°C): -2.859738511791204
p-value: 0.050234178440138645
ADF Statistic for Mean Temp (°C): -2.584580370038078
p-value: 0.09622625376032451
ADF Statistic for Heat Deg Days (°C): -2.8542701991278183
p-value: 0.050930040465753085
ADF Statistic for Cool Deg Days (°C): -9.518695440140341
p-value: 3.106690673697318e-16
  Summary of Regression Results   
Model:                         VAR
Method:                        OLS
Date:           Mon, 08, Apr, 2024
Time:                     00:35:57
--------------------------------------------------------------------
No. of Equations:         8.00000    BIC:                   -30.6019
Nobs:    

C:\Users\PC\anaconda3\envs\MachineLearning2\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  self._init_dates(dates, freq)
C:\Users\PC\anaconda3\envs\MachineLearning2\lib\site-packages\statsmodels\tsa\vector_ar\var_model.py:1559: RuntimeWarning: invalid value encountered in sqrt
  stderr = np.sqrt(np.diag(self.cov_params()))


array([[  1.20674421, -15.01958027,   1.47016405,   0.53768914,
        -23.66172658, -19.3723523 ,  37.24872516,  -0.12362714],
       [  1.1770624 ,  -8.7028229 ,   1.49252371,  -0.10309214,
        -18.47915757, -13.60774447,  31.48093597,  -0.1268085 ],
       [  1.1883505 ,  -2.68588248,   1.50305101,   1.47646045,
        -13.40480183,  -8.05097317,  26.12425442,   0.07328125],
       [  1.18325973,   2.12501649,   1.54773766,   1.60788434,
         -9.05475564,  -3.46711086,  21.66109513,   0.19398427],
       [  1.18573834,   4.82525917,   1.61755799,   1.63569063,
         -6.45216059,  -0.81302903,  19.05155475,   0.23852571]])

# Prince Edward

In [17]:
import pandas as pd
from statsmodels.tsa.api import VAR
from statsmodels.tsa.stattools import adfuller

# Assuming 'ConstructionBreton' is your DataFrame containing the data
TransportationSummerside = pd.read_excel('FinalPE.xlsx')
Transportation_Summerside = TransportationSummerside[TransportationSummerside['Station Name'] == 'Summerside']
Transportation_Summerside.set_index('Date', inplace=True)

# Selecting columns to include in the analysis, excluding 'provincename', 'Population', 'Station Name', 'Longitude (x)', and 'Latitude (y)'
variables = Transportation_Summerside.drop(columns=['provincename', 'Population', 'Station Name', 'Longitude (x)', 'Latitude (y)','Construction','Agriculture','Cool Deg Days (°C)'])

# Check for stationarity using Augmented Dickey-Fuller test
for column in variables.columns:
    result = adfuller(variables[column])
    print(f'ADF Statistic for {column}: {result[0]}')
    print(f'p-value: {result[1]}')

# Define lag order for VAR model
lag_order = 2  # Adjust as needed

# Fit VAR model
model = VAR(variables)
results = model.fit(lag_order)

# Print summary of the model
print(results.summary())

# Forecast future values
forecast = results.forecast(variables.values[-lag_order:], steps=5)  # Adjust 'steps' for desired forecast horizon
forecast


ADF Statistic for Transportation: -4.519791560778071
p-value: 0.00018106660858660208
ADF Statistic for Max Temp (°C): -1.626726595395562
p-value: 0.46920460353249904
ADF Statistic for Total Snow (cm): -2.9548200367132536
p-value: 0.03933451068942941
ADF Statistic for Total Precip (mm): -4.980294114194797
p-value: 2.4274842566178677e-05
ADF Statistic for Min Temp (°C): -1.3939369893456943
p-value: 0.5851793256540533
ADF Statistic for Mean Temp (°C): -1.4255718608705827
p-value: 0.5699571202581581
ADF Statistic for Heat Deg Days (°C): -1.1825543944366008
p-value: 0.6810549914808093
  Summary of Regression Results   
Model:                         VAR
Method:                        OLS
Date:           Mon, 08, Apr, 2024
Time:                     00:34:34
--------------------------------------------------------------------
No. of Equations:         7.00000    BIC:                    3.02303
Nobs:                     106.000    HQIC:                   1.45404
Log likelihood:          -96

C:\Users\PC\anaconda3\envs\MachineLearning2\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  self._init_dates(dates, freq)


array([[10.98124187,  3.03288253,  0.2895753 , -0.28315368, -4.14735029,
        -0.55509319, 18.81848162],
       [10.83889766,  4.65996872,  0.44297473,  0.7784207 , -3.779299  ,
         0.44647613, 17.82641745],
       [10.60683359,  6.39423286,  0.62927531,  0.35627626, -2.12253774,
         2.13883639, 16.14924037],
       [10.49572523,  8.35246787,  0.79895448,  0.26063657, -0.54360561,
         3.90863092, 14.58664617],
       [10.61811701,  9.41494487,  0.93164085,  0.52439164,  0.7717234 ,
         5.10070247, 13.39200008]])

In [15]:
import pandas as pd
from statsmodels.tsa.api import VAR
from statsmodels.tsa.stattools import adfuller

# Assuming 'ConstructionBreton' is your DataFrame containing the data
AgricultureEastpoint = pd.read_excel('FinalPE.xlsx')
Agriculture_Eastpoint = AgricultureEastpoint[AgricultureEastpoint['Station Name'] == 'East Point']
Agriculture_Eastpoint.set_index('Date', inplace=True)

# Selecting columns to include in the analysis, excluding 'provincename', 'Population', 'Station Name', 'Longitude (x)', and 'Latitude (y)'
variables = Agriculture_Eastpoint.drop(columns=['provincename', 'Population', 'Station Name', 'Longitude (x)', 'Latitude (y)','Construction','Transportation','Cool Deg Days (°C)'])

# Check for stationarity using Augmented Dickey-Fuller test
for column in variables.columns:
    result = adfuller(variables[column])
    print(f'ADF Statistic for {column}: {result[0]}')
    print(f'p-value: {result[1]}')

# Define lag order for VAR model
lag_order = 2  # Adjust as needed

# Fit VAR model
model = VAR(variables)
results = model.fit(lag_order)

# Print summary of the model
print(results.summary())

# Forecast future values
forecast = results.forecast(variables.values[-lag_order:], steps=5)  # Adjust 'steps' for desired forecast horizon
forecast


ADF Statistic for Agriculture: -3.0756737520087225
p-value: 0.02840660602081958
ADF Statistic for Max Temp (°C): -6.983671089484792
p-value: 8.070915757232442e-10
ADF Statistic for Total Snow (cm): -1.1286605969505494
p-value: 0.7035081364158068
ADF Statistic for Total Precip (mm): -9.801694835159335
p-value: 5.97148891631592e-17
ADF Statistic for Min Temp (°C): -2.4335622035290494
p-value: 0.132486881521385
ADF Statistic for Mean Temp (°C): -7.655652312678146
p-value: 1.7419174510130127e-11
ADF Statistic for Heat Deg Days (°C): -7.548775217123246
p-value: 3.230286330046229e-11
  Summary of Regression Results   
Model:                         VAR
Method:                        OLS
Date:           Mon, 08, Apr, 2024
Time:                     00:34:10
--------------------------------------------------------------------
No. of Equations:         7.00000    BIC:                    1.81239
Nobs:                     106.000    HQIC:                  0.243396
Log likelihood:          -904.

C:\Users\PC\anaconda3\envs\MachineLearning2\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  self._init_dates(dates, freq)


array([[ 0.64795313,  5.08005071,  7.2356285 ,  9.76115002, -2.6031298 ,
         1.20492577, 16.62030823],
       [ 0.62138535,  6.79018551,  6.99021874,  7.46195675, -0.68992105,
         3.13807419, 14.42748962],
       [ 0.59415045, 10.17131297,  6.77513732,  6.68261227,  2.29481765,
         6.24581445, 11.82878803],
       [ 0.57826426, 12.38160833,  6.61796373,  6.38615629,  4.49316473,
         8.44523647,  9.75592306],
       [ 0.56739684, 13.46987336,  6.45958601,  6.63625562,  5.74778583,
         9.63158066,  8.51182042]])